IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'sp_GetDonVi')
exec('CREATE PROCEDURE sp_GetDonVi AS BEGIN SET NOCOUNT ON; END')
GO
ALTER PROCEDURE sp_GetDonVi
	@lang INT = 0,
	@Username NVARCHAR(20)
AS
BEGIN
SELECT MSDV,TEN_DON_VI,TEN_NGAN,DIA_CHI,DIEN_THOAI,FAX,SO_TAI_KHOAN,TEN_NGAN_HANG FROM dbo.DON_VI
END	