IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'spGetMenuLeft')
exec('CREATE PROCEDURE spGetMenuLeft AS BEGIN SET NOCOUNT ON; END')
GO
ALTER PROCEDURE spGetMenuLeft
	@Username NVARCHAR(100) = 'ADMIN',
	@NNgu INT = 0,
	@IdCha INT = 2
AS 
BEGIN

SELECT T3.[ID_MENU],[KEY_MENU],CASE @NNgu WHEN 0 THEN T3.[TEN_MENU] WHEN 1 THEN ISNULL(NULLIF(T3.[TEN_MENU_ANH],''),T3.[TEN_MENU]) ELSE ISNULL(NULLIF(T3.[TEN_MENU_HOA],''),T3.[TEN_MENU]) END AS NAME,[ROOT],[HIDE],[BACK_COLOR],[IMG],[STT_MENU]	   
FROM NHOM_MENU T1 INNER JOIN dbo.USERS T2 ON T1.ID_NHOM = T2.ID_NHOM INNER JOIN dbo.MENU T3 ON T1.ID_MENU = T3.ID_MENU WHERE T2.USER_NAME = @Username AND	
[ROOT] = @IdCha ORDER BY [STT_MENU],[TEN_MENU]

END	

