IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'spGetListXiNghiep')
exec('CREATE PROCEDURE spGetListXiNghiep AS BEGIN SET NOCOUNT ON; END')
GO
ALTER PROCEDURE spGetListXiNghiep
	@Username NVARCHAR(100) ='huong',
	@NNgu INT =0
AS
BEGIN
SELECT  ID_XN,TEN_XN INTO #TEMP  FROM dbo.MGetToUser(@Username,@NNgu)
SELECT * FROM dbo.XI_NGHIEP

SELECT DISTINCT T1.ID_DV,T1.MS_XN, T2.TEN_XN,T1.STT_XN,T1.GOP_PB,T1.GOP_TH
FROM dbo.XI_NGHIEP T1
INNER JOIN #TEMP T2 ON T1.ID_XN = T2.ID_XN
UNION
SELECT DISTINCT T1.ID_DV,MS_XN,CASE @NNgu WHEN 0 THEN T1.TEN_XN WHEN 1 THEN ISNULL(NULLIF(T1.TEN_XN_ANH,''),T1.TEN_XN) ELSE ISNULL(NULLIF(T1.TEN_XN_HOA,''),T1.TEN_XN) END 
AS TEN_XN,STT_XN,T1.GOP_PB,T1.GOP_TH
FROM dbo.XI_NGHIEP T1 WHERE ID_DV NOT IN (
SELECT DISTINCT ID_DV FROM dbo.XI_NGHIEP WHERE ID_DV  IN (SELECT DISTINCT T1.ID_DV FROM dbo.XI_NGHIEP T1 WHERE T1.ID_XN IN (SELECT ID_XN FROM dbo.[TO])))
END

