IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'spGetUserbyGroup')
exec('CREATE PROCEDURE spGetUserbyGroup AS BEGIN SET NOCOUNT ON; END')
GO
ALTER PROCEDURE spGetUserbyGroup
	@ID_NHOM BIGINT,
	@Username NVARCHAR(100) ='admin',
	@NNgu INT =0
AS
BEGIN
SELECT ID_USER,ID_CN,[USER_NAME],FULL_NAME,PASSWORD,DESCRIPTION,USER_MAIL,ACTIVE FROM dbo.USERS
WHERE ID_NHOM =@ID_NHOM
END
