IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'spGetAllNhom')
exec('CREATE PROCEDURE spGetAllNhom AS BEGIN SET NOCOUNT ON; END')
GO
ALTER PROCEDURE spGetAllNhom
	@Username NVARCHAR(100) ='admin',
	@NNgu INT =0
AS
BEGIN
SELECT ID_NHOM,CASE @NNgu WHEN 0 THEN T1.TEN_NHOM WHEN 1 THEN ISNULL(NULLIF(T1.TEN_NHOM_ANH,''),T1.TEN_NHOM) ELSE ISNULL(NULLIF(T1.TEN_NHOM_HOA,''),T1.TEN_NHOM) END 
AS TEN_NHOM,GHI_CHU FROM dbo.NHOM T1
END
