IF NOT EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'spGetListDonVi')
exec('CREATE PROCEDURE spGetListDonVi AS BEGIN SET NOCOUNT ON; END')
GO
ALTER PROCEDURE spGetListDonVi
	@Username NVARCHAR(100) ='HUONG',
	@NNgu INT =0
AS
BEGIN
SELECT  ID_DV,TEN_DON_VI INTO #TEMP  FROM dbo.MGetToUser(@Username,@NNgu)

SELECT DISTINCT T1.ID_DV,MSDV, T2.TEN_DON_VI,T1.DIA_CHI,T1.DIEN_THOAI,T1.FAX,T1.SO_TAI_KHOAN,T1.TEN_NGAN_HANG 
FROM dbo.DON_VI T1
INNER JOIN #TEMP T2 ON T1.ID_DV = T2.ID_DV
UNION
--SELECT DISTINCT T1.ID_DV,MSDV,CASE @NNgu WHEN 0 THEN T1.TEN_DON_VI WHEN 1 THEN ISNULL(NULLIF(T1.TEN_DON_VI_ANH,''),T1.TEN_DON_VI) ELSE ISNULL(NULLIF(T1.TEN_DON_VI_HOA,''),T1.TEN_DON_VI) END 
--AS TEN_DON_VI,T1.DIA_CHI,T1.DIEN_THOAI,T1.FAX,T1.SO_TAI_KHOAN,T1.TEN_NGAN_HANG
--FROM dbo.DON_VI T1 WHERE ID_DV NOT IN (
--SELECT DISTINCT ID_DV FROM dbo.XI_NGHIEP WHERE ID_DV  IN (SELECT DISTINCT T1.ID_DV FROM dbo.XI_NGHIEP T1 WHERE T1.ID_XN IN (SELECT ID_XN FROM dbo.[TO])))
SELECT DISTINCT T1.ID_DV,T1.MSDV,CASE @NNgu WHEN 0 THEN T1.TEN_DON_VI WHEN 1 THEN ISNULL(NULLIF(T1.TEN_DON_VI_ANH,''),T1.TEN_DON_VI) ELSE ISNULL(NULLIF(T1.TEN_DON_VI_HOA,''),T1.TEN_DON_VI) END 
AS TEN_DON_VI,T1.DIA_CHI,T1.DIEN_THOAI,T1.FAX,T1.SO_TAI_KHOAN,T1.TEN_NGAN_HANG
FROM dbo.DON_VI T1 LEFT JOIN dbo.XI_NGHIEP T2 ON T2.ID_DV = T1.ID_DV LEFT JOIN dbo.[TO] T3 ON T3.ID_XN = T2.ID_XN
GROUP BY T1.ID_DV,T1.MSDV,CASE @NNgu WHEN 0 THEN T1.TEN_DON_VI WHEN 1 THEN ISNULL(NULLIF(T1.TEN_DON_VI_ANH,''),T1.TEN_DON_VI) ELSE ISNULL(NULLIF(T1.TEN_DON_VI_HOA,''),T1.TEN_DON_VI) END ,T1.DIA_CHI,T1.DIEN_THOAI,T1.FAX,T1.SO_TAI_KHOAN,T1.TEN_NGAN_HANG
HAVING COUNT(T3.ID_TO) = 0

END

